# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trivy.proto

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="trivy.proto",
    package="trivy.detector",
    syntax="proto3",
    serialized_options=_b("Z\010detector"),
    serialized_pb=_b(
        '\n\x0btrivy.proto\x12\x0etrivy.detector"`\n\x0fOSDetectRequest\x12\x11\n\tos_family\x18\x01 \x01(\t\x12\x0f\n\x07os_name\x18\x02 \x01(\t\x12)\n\x08packages\x18\x03 \x03(\x0b\x32\x17.trivy.detector.Package"Y\n\x0e\x44\x65tectResponse\x12G\n\x18\x64\x65tected_vulnerabilities\x18\x01 \x03(\x0b\x32%.trivy.detector.DetectedVulnerability"\xa5\x01\n\x07Package\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07release\x18\x03 \x01(\t\x12\r\n\x05\x65poch\x18\x04 \x01(\x05\x12\x0c\n\x04\x61rch\x18\x05 \x01(\t\x12\x10\n\x08src_name\x18\x06 \x01(\t\x12\x13\n\x0bsrc_version\x18\x07 \x01(\t\x12\x13\n\x0bsrc_release\x18\x08 \x01(\t\x12\x11\n\tsrc_epoch\x18\t \x01(\x05"Q\n\x10LibDetectRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12*\n\tlibraries\x18\x02 \x03(\x0b\x32\x17.trivy.detector.Library"(\n\x07Library\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t"\xbf\x01\n\x15\x44\x65tectedVulnerability\x12\x18\n\x10vulnerability_id\x18\x01 \x01(\t\x12\x10\n\x08pkg_name\x18\x02 \x01(\t\x12\x19\n\x11installed_version\x18\x03 \x01(\t\x12\x15\n\rfixed_version\x18\x04 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x10\n\x08severity\x18\x07 \x01(\t\x12\x12\n\nreferences\x18\x08 \x03(\t2W\n\nOSDetector\x12I\n\x06\x44\x65tect\x12\x1f.trivy.detector.OSDetectRequest\x1a\x1e.trivy.detector.DetectResponse2Y\n\x0bLibDetector\x12J\n\x06\x44\x65tect\x12 .trivy.detector.LibDetectRequest\x1a\x1e.trivy.detector.DetectResponseB\nZ\x08\x64\x65tectorb\x06proto3'
    ),
)


_OSDETECTREQUEST = _descriptor.Descriptor(
    name="OSDetectRequest",
    full_name="trivy.detector.OSDetectRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="os_family",
            full_name="trivy.detector.OSDetectRequest.os_family",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="os_name",
            full_name="trivy.detector.OSDetectRequest.os_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="packages",
            full_name="trivy.detector.OSDetectRequest.packages",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=31,
    serialized_end=127,
)


_DETECTRESPONSE = _descriptor.Descriptor(
    name="DetectResponse",
    full_name="trivy.detector.DetectResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="detected_vulnerabilities",
            full_name="trivy.detector.DetectResponse.detected_vulnerabilities",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=129,
    serialized_end=218,
)


_PACKAGE = _descriptor.Descriptor(
    name="Package",
    full_name="trivy.detector.Package",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="trivy.detector.Package.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="version",
            full_name="trivy.detector.Package.version",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="release",
            full_name="trivy.detector.Package.release",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="epoch",
            full_name="trivy.detector.Package.epoch",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="arch",
            full_name="trivy.detector.Package.arch",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="src_name",
            full_name="trivy.detector.Package.src_name",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="src_version",
            full_name="trivy.detector.Package.src_version",
            index=6,
            number=7,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="src_release",
            full_name="trivy.detector.Package.src_release",
            index=7,
            number=8,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="src_epoch",
            full_name="trivy.detector.Package.src_epoch",
            index=8,
            number=9,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=221,
    serialized_end=386,
)


_LIBDETECTREQUEST = _descriptor.Descriptor(
    name="LibDetectRequest",
    full_name="trivy.detector.LibDetectRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="file_path",
            full_name="trivy.detector.LibDetectRequest.file_path",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="libraries",
            full_name="trivy.detector.LibDetectRequest.libraries",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=388,
    serialized_end=469,
)


_LIBRARY = _descriptor.Descriptor(
    name="Library",
    full_name="trivy.detector.Library",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="trivy.detector.Library.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="version",
            full_name="trivy.detector.Library.version",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=471,
    serialized_end=511,
)


_DETECTEDVULNERABILITY = _descriptor.Descriptor(
    name="DetectedVulnerability",
    full_name="trivy.detector.DetectedVulnerability",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="vulnerability_id",
            full_name="trivy.detector.DetectedVulnerability.vulnerability_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="pkg_name",
            full_name="trivy.detector.DetectedVulnerability.pkg_name",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="installed_version",
            full_name="trivy.detector.DetectedVulnerability.installed_version",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="fixed_version",
            full_name="trivy.detector.DetectedVulnerability.fixed_version",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="title",
            full_name="trivy.detector.DetectedVulnerability.title",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="description",
            full_name="trivy.detector.DetectedVulnerability.description",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="severity",
            full_name="trivy.detector.DetectedVulnerability.severity",
            index=6,
            number=7,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="references",
            full_name="trivy.detector.DetectedVulnerability.references",
            index=7,
            number=8,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=514,
    serialized_end=705,
)

_OSDETECTREQUEST.fields_by_name["packages"].message_type = _PACKAGE
_DETECTRESPONSE.fields_by_name[
    "detected_vulnerabilities"
].message_type = _DETECTEDVULNERABILITY
_LIBDETECTREQUEST.fields_by_name["libraries"].message_type = _LIBRARY
DESCRIPTOR.message_types_by_name["OSDetectRequest"] = _OSDETECTREQUEST
DESCRIPTOR.message_types_by_name["DetectResponse"] = _DETECTRESPONSE
DESCRIPTOR.message_types_by_name["Package"] = _PACKAGE
DESCRIPTOR.message_types_by_name["LibDetectRequest"] = _LIBDETECTREQUEST
DESCRIPTOR.message_types_by_name["Library"] = _LIBRARY
DESCRIPTOR.message_types_by_name["DetectedVulnerability"] = _DETECTEDVULNERABILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OSDetectRequest = _reflection.GeneratedProtocolMessageType(
    "OSDetectRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _OSDETECTREQUEST,
        "__module__": "trivy_pb2"
        # @@protoc_insertion_point(class_scope:trivy.detector.OSDetectRequest)
    },
)
_sym_db.RegisterMessage(OSDetectRequest)

DetectResponse = _reflection.GeneratedProtocolMessageType(
    "DetectResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _DETECTRESPONSE,
        "__module__": "trivy_pb2"
        # @@protoc_insertion_point(class_scope:trivy.detector.DetectResponse)
    },
)
_sym_db.RegisterMessage(DetectResponse)

Package = _reflection.GeneratedProtocolMessageType(
    "Package",
    (_message.Message,),
    {
        "DESCRIPTOR": _PACKAGE,
        "__module__": "trivy_pb2"
        # @@protoc_insertion_point(class_scope:trivy.detector.Package)
    },
)
_sym_db.RegisterMessage(Package)

LibDetectRequest = _reflection.GeneratedProtocolMessageType(
    "LibDetectRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LIBDETECTREQUEST,
        "__module__": "trivy_pb2"
        # @@protoc_insertion_point(class_scope:trivy.detector.LibDetectRequest)
    },
)
_sym_db.RegisterMessage(LibDetectRequest)

Library = _reflection.GeneratedProtocolMessageType(
    "Library",
    (_message.Message,),
    {
        "DESCRIPTOR": _LIBRARY,
        "__module__": "trivy_pb2"
        # @@protoc_insertion_point(class_scope:trivy.detector.Library)
    },
)
_sym_db.RegisterMessage(Library)

DetectedVulnerability = _reflection.GeneratedProtocolMessageType(
    "DetectedVulnerability",
    (_message.Message,),
    {
        "DESCRIPTOR": _DETECTEDVULNERABILITY,
        "__module__": "trivy_pb2"
        # @@protoc_insertion_point(class_scope:trivy.detector.DetectedVulnerability)
    },
)
_sym_db.RegisterMessage(DetectedVulnerability)


DESCRIPTOR._options = None

_OSDETECTOR = _descriptor.ServiceDescriptor(
    name="OSDetector",
    full_name="trivy.detector.OSDetector",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=707,
    serialized_end=794,
    methods=[
        _descriptor.MethodDescriptor(
            name="Detect",
            full_name="trivy.detector.OSDetector.Detect",
            index=0,
            containing_service=None,
            input_type=_OSDETECTREQUEST,
            output_type=_DETECTRESPONSE,
            serialized_options=None,
        )
    ],
)
_sym_db.RegisterServiceDescriptor(_OSDETECTOR)

DESCRIPTOR.services_by_name["OSDetector"] = _OSDETECTOR


_LIBDETECTOR = _descriptor.ServiceDescriptor(
    name="LibDetector",
    full_name="trivy.detector.LibDetector",
    file=DESCRIPTOR,
    index=1,
    serialized_options=None,
    serialized_start=796,
    serialized_end=885,
    methods=[
        _descriptor.MethodDescriptor(
            name="Detect",
            full_name="trivy.detector.LibDetector.Detect",
            index=0,
            containing_service=None,
            input_type=_LIBDETECTREQUEST,
            output_type=_DETECTRESPONSE,
            serialized_options=None,
        )
    ],
)
_sym_db.RegisterServiceDescriptor(_LIBDETECTOR)

DESCRIPTOR.services_by_name["LibDetector"] = _LIBDETECTOR

# @@protoc_insertion_point(module_scope)
